steps:
  # Configura el entorno
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['config', 'set', 'project', 'bootcamp-thebridgecloud']

  # Construye la imagen del contenedor
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bootcamp-thebridgecloud/nodegabi', '.']

  # Sube la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bootcamp-thebridgecloud/nodegabi']

  # Implementa la imagen en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args: [
        "-c",
        "gcloud run deploy mi-servicio-nodegabi 
        - --image=gcr.io/bootcamp-thebridgecloud/nodegabi
        - --region=europe-west1
        - --platform=managed
        - --allow-unauthenticated
        - --port=3000
        - --update-env-vars DB_URL_ATLAS=$$DB_URL_ATLAS"
    ]
    secretEnv: [
      'DB_URL_ATLAS'
    ]
availableSecrets:
  secretManager:
    - versionName: projects/180585318088/secrets/mongo/versions/latest
      env: DB_URL_ATLAS
        #- --update-env-vars
       # - DB_URL_ATLAS=mongodb+srv://crow262728:diego123@cluster0.17omynw.mongodb.net/mongoenlanube
