steps:
  # Configura el entorno
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['config', 'set', 'project', 'bootcamp-thebridgecloud']

  # Construye la imagen de la aplicación web
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/bootcamp-thebridgecloud/nodegabiserver', './server' ]

  # Sube la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/bootcamp-thebridgecloud/nodegabiserver' ]

  # Implementa la imagen en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args: [
      "-c",
      "gcloud run deploy mi-servicio-server 
        --image=gcr.io/bootcamp-thebridgecloud/nodegabiserver
        --region=europe-west1
        --platform=managed
        --allow-unauthenticated
        --port=3000
        --update-env-vars DB_URL_ATLAS=$$DB_URL_ATLAS"
    ]
    secretEnv: [
      'DB_URL_ATLAS'
    ]

  # Obtiene la URL del servidor desplegado
  - name: 'gcr.io/cloud-builders/gcloud'
    id: get-server-url
    args: [
      'run', 'services', 'describe', 'mi-servicio-server',
      '--region=europe-west1',
      '--format=value(status.url)',
      '--platform=managed'
    ]

  # Almacena la URL del servidor en una variable
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args: [
      '-c',
      'export SERVER_URL=$(cat ${_GET_SERVER_URL_OUTPUT_FILE})'
    ]
    env:
      - '_GET_SERVER_URL_OUTPUT_FILE=/workspace/server-url.txt'

  # Lee la URL del servidor desde el archivo
  - name: 'gcr.io/cloud-builders/gcloud'
    id: read-server-url
    entrypoint: bash
    args: [
          '-c',
          'export SERVER_URL=$(cat /workspace/server-url.txt)'
        ]

  # Construye la imagen de la aplicación web
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/bootcamp-thebridgecloud/nodegabiclient', './client' ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/bootcamp-thebridgecloud/nodegabiclient' ]

  # Implementa la imagen de la aplicación web en Cloud Run y pasa la URL del servidor como variable de entorno
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args: [
        '-c',
        "gcloud run deploy mi-servicio-client 
        --image=gcr.io/bootcamp-thebridgecloud/nodegabiclient
        --region=europe-west1  
        --platform=managed 
        --allow-unauthenticated  
        --port=5173
        --update-env-vars DB_URL_ATLAS=$$DB_URL_ATLAS
        --update-env-vars SERVER_URL=$$SERVER_URL"
    ]

availableSecrets:
  secretManager:
    - versionName: projects/180585318088/secrets/mongo/versions/latest
      env: DB_URL_ATLAS
